# Generated by Django 3.2.23 on 2023-12-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Tasks',
        ),
    ]
